name: llm_model
description: LLM offline demo with first-run model download and FFI (v2 embedding kept)

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  ffi: ^2.1.2
  geolocator: ^13.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/